# Generated by Django 5.0 on 2024-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candles", "0003_category_product_seller_inventory_cart_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="category_images/"),
        ),
    ]
