# Generated by Django 5.0 on 2024-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candles", "0004_remove_category_icon_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="MRP",
        ),
        migrations.AlterField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
